// src/data/parts.ts
export const parts = [
    {
        id: "luna", name: "LUNA", basePath: "/characters/Luna/Luna_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "spike", name: "SPIKE", basePath: "/characters/Spike/Spike_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "nox", name: "NOX", basePath: "/characters/Nox/Nox_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "dime", name: "DIME", basePath: "/characters/Dime/Dime_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "bogg", name: "BOGG", basePath: "/characters/Bogg/Bogg_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "slinky", name: "SLINKY", basePath: "/characters/Slinky/Slinky_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "sunny", name: "SUNNY", basePath: "/characters/Sunny/Sunny_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "muff", name: "MUFF", basePath: "/characters/Muff/Muff_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "bruno", name: "BRUNO", basePath: "/characters/Bruno/Bruno_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "bob", name: "BOB", basePath: "/characters/Bob/Bob_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "willy", name: "WILLY", basePath: "/characters/Willy/Willy_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
    {
        id: "pooh", name: "POOH", basePath: "/characters/Pooh/Pooh_",
        colors: ["353432", "9fd6ff", "aa9e92", "fee98e", "ff953f"],
        hasFace: true,
        hasArms: true,
        hasMouth: true,
    },
];
